const fs=require('fs'),path=require('path');
const sharp=require(process.env.SHARP_MODULE || 'C:/Users/namba/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const dir=__dirname;
const targets={bookshelf:[364,226,279,374],network:[1302,299,130,333],clock:[638,291,70,81],'fan-1':[1080,236,85,97],'fan-2':[1170,218,96,102],bed:[14,435,588,299],desk:[653,449,494,168],compute:[1345,508,307,249],display:[860,350,371,150],external:[1477,606,175,212],chair:[742,395,179,230]};
const variants={'bookshelf-empty':'bookshelf','bed-medium':'bed','bed-low':'bed','desk-stacked':'desk'};
async function bounds(file){const {data,info}=await sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true});let l=info.width,t=info.height,r=0,b=0,count=0;const rows=new Uint32Array(info.height),cols=new Uint32Array(info.width);for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>128){rows[y]++;cols[x]++;count++;}for(let y=0;y<info.height;y++)if(rows[y]>8){t=Math.min(t,y);b=y;}for(let x=0;x<info.width;x++)if(cols[x]>8){l=Math.min(l,x);r=x;}return {rect:[l,t,r-l+1,b-t+1],width:info.width,height:info.height,transparent:count<info.width*info.height*.99};}
(async()=>{const catalog=JSON.parse(fs.readFileSync(path.resolve(dir,'../../avatar-motion/Assets/room-components.json').replace('Asset/avatar-motion','avatar-motion'),'utf8'));const assets={};for(const file of fs.readdirSync(dir).filter(x=>x.endsWith('.png')&&!x.startsWith('preview')&&!x.startsWith('contact'))){assets[file.slice(0,-4)]=await bounds(path.join(dir,file));}
const components=catalog.components.map(c=>({id:c.id,title:c.title,category:c.category,z:c.z,file:c.id+'.png',sourceRect:assets[c.id].rect,targetRect:targets[c.id],variants:Object.keys(variants).filter(v=>variants[v]===c.id).map(v=>v+'.png')}));
fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({canvas:[1672,941],background:'background.png',source:'source-room.png',note:'Generated extraction with reconstructed occluded surfaces. sourceRect maps to targetRect; state variants use the same base transform. Not pixel-identical to source.',components,assets},null,2));
for(const mode of ['normal','states']){const layers=[];for(const c of components.sort((a,b)=>a.z-b.z)){const id=mode==='states'?({'bed':'bed-low','bookshelf':'bookshelf-empty','desk':'desk-stacked'}[c.id]||c.id):c.id;const v=assets[id].rect,s=c.sourceRect,d=c.targetRect,sx=d[2]/s[2],sy=d[3]/s[3];const input=await sharp(path.join(dir,id+'.png')).extract({left:v[0],top:v[1],width:v[2],height:v[3]}).resize(Math.round(v[2]*sx),Math.round(v[3]*sy),{fit:'fill'}).toBuffer();layers.push({input,left:Math.round(d[0]+(v[0]-s[0])*sx),top:Math.round(d[1]+(v[1]-s[1])*sy)});}await sharp(path.join(dir,'background.png')).resize(1672,941).composite(layers).png().toFile(path.join(dir,'preview-'+mode+'.png'));}
const names=Object.keys(assets).filter(n=>!['source-room','bed-perspective-v2-cutout'].includes(n));const tiles=[];for(let i=0;i<names.length;i++){let n=names[i],r=assets[n].rect;const input=await sharp(path.join(dir,n+'.png')).extract({left:r[0],top:r[1],width:r[2],height:r[3]}).resize(380,215,{fit:'contain',background:'#e6e9ee'}).png().toBuffer();tiles.push({input,left:(i%4)*400+10,top:Math.floor(i/4)*250+25});const label=Buffer.from('<svg width="390" height="25"><text x="5" y="18" font-size="16">'+n+'</text></svg>');tiles.push({input:label,left:(i%4)*400+5,top:Math.floor(i/4)*250});}await sharp({create:{width:1600,height:Math.ceil(names.length/4)*250,channels:4,background:'#e6e9ee'}}).composite(tiles).png().toFile(path.join(dir,'contact-sheet.png'));console.log(JSON.stringify({files:Object.keys(assets).length,opaqueComponents:Object.entries(assets).filter(([n,a])=>!a.transparent&&!['background','source-room'].includes(n)).map(([n])=>n)}));})();
